---
default_language_version:
    python: python3.10
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-toml
          - id: check-yaml
          - id: pretty-format-json
            args: [--autofix]
          - id: trailing-whitespace
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
    - repo: https://github.com/ambv/black
      rev: 22.10.0
      hooks:
          - id: black
    - repo: https://github.com/pycqa/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.28.0  # or higher tag
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict, '-d {rules: {line-length: disable}}']
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2  # or other specific tag
      hooks:
          - id: yamlfmt
    - repo: https://github.com/sqlfluff/sqlfluff
      rev: 1.4.2
      hooks:
          - id: sqlfluff-lint
            args: [--dialect, snowflake]
          - id: sqlfluff-fix
            args: [--force, --dialect, snowflake]
    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: script-must-have-extension
          - id: script-must-not-have-extension
    - repo: local
      hooks:
          - id: jupyter-nb-clear-output
            name: jupyter-nb-clear-output
            files: \.ipynb$
            language: system
            entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
    - repo: https://github.com/nbQA-dev/nbQA
      rev: 1.5.3
      hooks:
          - id: nbqa-black
          - id: nbqa-isort
          - id: nbqa-flake8
    - repo: https://github.com/python-poetry/poetry
      rev: 1.2.1
      hooks:
          - id: poetry-check
          - id: poetry-lock
            stages: [push]
            files: ^(pyproject.toml)|(poetry.lock)$
